[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    '@openzeppelin=lib/openzeppelin-contracts/',
    'openzeppelin/=lib/openzeppelin-contracts/contracts/',
    'superfluid-contracts/=lib/protocol-monorepo/packages/ethereum-contracts/contracts/',
    '@superfluid-finance/ethereum-contracts/=lib/protocol-monorepo/packages/ethereum-contracts'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
