[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'superfluid-contracts/=lib/protocol-monorepo/packages/ethereum-contracts/contracts/',
    '@superfluid-finance/ethereum-contracts/=lib/protocol-monorepo/packages/ethereum-contracts',
    '@superfluid-finance/ethereum-contracts/=packages/ethereum-contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
